const { addAdmin, updateAdmin, getAdminsBySuperAdmin, getAdmin, deleteAdmin, createOrganization, updateOrganization, getAllOrganizations, getOrganization, getOrganizationForLoggedInUser, deleteOrganization, decryptPassword } = require("./SuperAdminController");
const { getAdminsByAdmin, createPermission, updatePermission, getAllPermissions, getPermission, deletePermission, createRole, updateRole, getAllRoles, getRole, deleteRole, createDepartment, updateDepartment, getAllDepartments, getDepartment, deleteDepartment } = require("./AdminController");
const { addEmployee, updateEmployee, getAllEmployees, getEmployee, deleteEmployee, assignAsset, updateAsset, getAllAssets, getAssetsForEmployee, getAsset, getAllResignationRequests, handleResignationRequest, createPayrollRecord, updateEmployeeDeductions, getPayrollRecords, getPayrollRecord, CreatePolicy, UpdatePolicy, DeletePolicy, GetPolicy, CreateAnnouncement, UpdateAnnouncement, DeleteAnnouncement, getAllAnnouncements, getAnnouncement, createHoliday, updateHoliday, getAllHolidays, getHoliday, deleteHoliday } = require("./HrController")
const { createProject, updateProject, getAllProjects, getProject, deleteProject } = require("./ManagerController")
const { createTask, updateTask, getAllTasks, getTask, deleteTask, approveOrRejectLeaveRequest, getLeaveRequestsByManager } = require("./TlController")
const { PersonalDetails, updatePersonalDetails, getEmployees, createLeaveRequest, updateLeaveRequest, deleteLeaveRequest, getLeaveRequestsForLoggedInEmployee, getLeaveRequestsForemployee, getLeave, applyForResignation, markAttendance, markCheckIn, markCheckOut, getAttendanceRecords, getAttendanceRecordsForEmployee, getPolicies, getAttendanceRecordsForAllEmployees } = require("./EmployeeController")


module.exports = { addAdmin, updateAdmin, getAdminsBySuperAdmin, getAdmin, deleteAdmin, createOrganization, updateOrganization, getAllOrganizations, getOrganization, getOrganizationForLoggedInUser, deleteOrganization, decryptPassword,
    getAdminsByAdmin, createPermission, updatePermission, getAllPermissions, getPermission, deletePermission, createRole, updateRole, getAllRoles, getRole, deleteRole, createDepartment, updateDepartment, getAllDepartments, getDepartment, deleteDepartment,
    addEmployee, updateEmployee, getAllEmployees, getEmployee, deleteEmployee, assignAsset, updateAsset, getAllAssets, getAssetsForEmployee, getAsset, getAllResignationRequests, handleResignationRequest, createPayrollRecord, updateEmployeeDeductions, getPayrollRecords, getPayrollRecord, CreatePolicy, UpdatePolicy, DeletePolicy, GetPolicy, CreateAnnouncement, UpdateAnnouncement, DeleteAnnouncement, getAllAnnouncements, getAnnouncement, createHoliday, updateHoliday, getAllHolidays, getHoliday, deleteHoliday,
    createProject, updateProject, getAllProjects, getProject, deleteProject,
    createTask, updateTask, getAllTasks, getTask, deleteTask, approveOrRejectLeaveRequest, getLeaveRequestsByManager,
    PersonalDetails, updatePersonalDetails, getEmployees, createLeaveRequest, updateLeaveRequest, deleteLeaveRequest, getLeaveRequestsForLoggedInEmployee, getLeaveRequestsForemployee, getLeave, applyForResignation, markAttendance, markCheckIn, markCheckOut, getAttendanceRecords, getAttendanceRecordsForEmployee, getPolicies, getAttendanceRecordsForAllEmployees };   
